name: spark_app
description: Your driving buddy.

version: 1.0.1+4

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  alice: ^0.1.5
  basic_utils: ^2.6.3
  camera: ^0.5.8+2
  carousel_slider: ^2.3.1
  catcher: ^0.3.22
  cupertino_icons: ^1.0.0
  dartz: ^0.9.2
  dio: ^3.0.10
  dotted_border: ^1.0.7
  email_validator: ^1.0.5
  equatable: ^1.2.5
  expandable_bottom_sheet: ^0.2.1+1
  firebase_messaging: ^7.0.3
  flutter_bloc: 6.0.6
  flutter_feather_icons: ^1.0.3
  flutter_icons: ^1.1.0
  flutter_polyline_points: ^0.2.4
  flutter_secure_storage: ^3.3.5
  flutter_spinkit: ^4.1.2+1
  freezed_annotation: ^0.12.0
  geolocator: ^5.1.2
  get_version: ^0.2.2
  google_maps_flutter: ^0.5.30
  http: ^0.12.2
  intl: ^0.16.1
  json_serializable: ^3.5.0
  location: ^3.2.4
  logger: ^0.7.0
  logger_flutter: ^0.7.0
  path: ^1.6.4
  path_provider: ^1.6.11
  pointycastle: ^2.0.0
  pretty_dio_logger: ^1.1.1
  progress_dialog: ^1.2.4
  provider: ^4.3.2+2
  pull_to_refresh: ^1.6.2
  qr_flutter: ^3.2.0
  retrofit: ^1.3.4+1
  search_map_place: ^0.3.0
  shake: ^0.1.0
  shared_preferences: ^0.5.12+2
  simple_animations: ^2.2.2
  smooth_page_indicator: ^0.2.3
  supercharged: ^1.11.1
  uni_links: ^0.4.0
  url_launcher: ^5.7.8
  uuid: ^2.2.2
  webview_flutter: ^1.0.7
  flutter_svg: ^0.18.0
  fluttertoast: ^7.1.8
  qr_code_scanner: ^0.3.5
  rating_dialog: ^1.0.0
  store_redirect: ^1.0.1





dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^1.10.4
  flutter_launcher_icons: ^0.8.1
  freezed: ^0.12.2
  mockito: ^4.1.1
  pedantic: ^1.9.0
  retrofit_generator: ^1.4.0
#  flutter_native_splash: ^1.2.0

flutter:
  fonts:
    - family: CustomIcons
      fonts:
        - asset: assets/fonts/custom_icons.ttf
    - family: Montserrat
      fonts:
          - asset: assets/fonts/Montserrat-Regular.ttf
            weight: 400
          - asset: assets/fonts/Montserrat-Bold.ttf
            weight: 700
          - asset: assets/fonts/Montserrat-Light.ttf
            weight: 300
          - asset: assets/fonts/Montserrat-SemiBold.ttf
            weight: 600
          - asset: assets/fonts/Montserrat-Medium.ttf
            weight: 500

  assets:
    - assets/images/
  uses-material-design: true
