name: spark_app
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  alice: ^0.1.5
  basic_utils: ^2.6.3
  dartz: ^0.9.2
  dio: ^3.0.10
  equatable: ^1.2.5
  flutter_bloc: 6.0.6
  flutter_secure_storage: ^3.3.5
  freezed_annotation: ^0.12.0
  http: ^0.12.2
  intl: ^0.16.1
  json_serializable: ^3.5.0
  logger: ^0.7.0
  logger_flutter: ^0.7.0
  pointycastle: ^2.0.0
  pretty_dio_logger: ^1.1.1
  provider: ^4.3.2+2
  pull_to_refresh: ^1.6.2
  retrofit: ^1.3.4+1
  shake: ^0.1.0
  shared_preferences: ^0.5.12+2
  simple_animations: ^2.2.2
  supercharged: ^1.11.1
  uni_links: ^0.4.0
  url_launcher: ^5.7.8
  uuid: ^2.2.2
  webview_flutter: ^1.0.7
  catcher: ^0.3.22

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^1.10.4
  flutter_launcher_icons: ^0.8.1
  freezed: ^0.12.2
  mockito: ^4.1.1
  pedantic: ^1.9.0
  retrofit_generator: ^1.4.0

flutter:
  assets:
    - assets/images/
  uses-material-design: true

